export const actionTypes = {
  // Auth
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  SIGNUP_OTP: "SIGNUP_OTP",
  SIGNUP_PASSWORD: "SIGNUP_PASSWORD",
  LOGOUT: "LOGOUT",
  GET_ME: "GET_ME",
  TOKEN: "TOKEN",
  SIGNUPEMAILDATA: "SIGNUPEMAILDATA",
  LOGINEMAILDATA:"LOGINEMAILDATA",
  FORGET_NEW_PASSWORD: "FORGET_NEW_PASSWORD",
  UPDATE_NEW_PASSWORD: "UPDATE_NEW_PASSWORD",
  UPDATE_NAME:"UPDATE_NAME",
  CREATE_NEW_ADMIN: "CREATE_NEW_ADMIN",
  REMOVE_SCHOOL:"REMOVE_SCHOOL",
  REVOKE_SCHOOL:"REVOKE_SCHOOL",
  UN_REVOKE_SCHOOL:"UN_REVOKE_SCHOOL",
  DELETE_SUPER_ADMIN:"DELETE_SUPER_ADMIN",
  //   FORGOT_PASSWORD: "FORGOT_PASSWORD",
  SET_WAREHOUSE_ADDRESS: "SET_WAREHOUSE_ADDRESS",
  GET_LISTING_REQUEST_ORDERS: "GET_LISTING_REQUEST_ORDERS",
  PAYMENT_HISTORY_SCHOOL:"PAYMENT_HISTORY_SCHOOL",

  // Product
  ADD_PRODUCT: "ADD_PRODUCT",
  GET_GENERAL_ARTS: "GET_GENERAL_ARTS",
  GET_AUCTION_ARTS: "GET_AUCTION_ARTS",
  GET_MASTERPIECE_ARTS: "GET_MASTERPIECE_ARTS",
  GET_ALL_ARTS: "GET_ALL_ARTS",
  VIEW_ART: "VIEW_ART",
  GET_VENDORS_PRODUCTS_BY_CATEGORIES: "GET_VENDORS_PRODUCTS_BY_CATEGORIES",
  ENABLE_DISABLE_PRODUCT: "ENABLE_DISABLE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  GET_ALL_PRODUCTS_LIST_FOT_SEARCH: "GET_ALL_PRODUCTS_LIST_FOT_SEARCH",
  GET_PRODUCT_DETAILS_BY_ID: "GET_PRODUCT_DETAILS_BY_ID",
  GET_RESERVE_ARTS: "GET_RESERVE_ARTS",
  GET_TRADES: "GET_TRADES",
  DELETE_ART: "DELETE_ART",
  DELETE_AUCTION: "DELETE_AUCTION",
  UPDATE_ART: "UPDATE_ART",
  UPDATE_AUCTION_ART: "UPDATE_AUCTION_ART",
  GET_LISTING_APPROVED_ORDERS: "GET_LISTING_APPROVED_ORDERS",

  // orders
  GET_ALL_ORDERS: "GET_ALL_ORDERS",
  GET_PENDING_ORDERS: "GET_PENDING_ORDERS",
  GET_PORTRAIT_REQUEST_ORDERS: "GET_PORTRAIT_REQUEST_ORDERS",

  //dashboard
  GET_DASHBOARD_ORDERS: "GET_DASHBOARD_ORDERS",

  GET_PORTRAIT_ORDERS: "GET_PORTRAIT_ORDERS",

  SUCCESS: "SUCCESS",

  //notification
  GET_NOTIFICATION: "GET_NOTIFICATION",
  //Artist request
  GET_ARTIST_REQUEST: "GET_ARTIST_REQUEST",
  GET_ARTIST: "GET_ARTIST",
  APPROVED_ARTIST: "APPROVED_ARTIST",

  //finance
  GET_TRANSACTION_OVERVIEW: "GET_TRANSACTION_OVERVIEW",

  //charges
  GET_CHARGES: "GET_CHARGES",
  SET_CHARGES: "SET_CHARGES",

  GET_ALL_SCHOOLS: "GET_ALL_SCHOOLS",
  REVOKE_SCHOOL: "REVOKE_SCHOOL",
  UNREVOKE_SCHOOL: "UNREVOKE_SCHOOL",
  GET_ALL_ADMINS: "GET_ALL_ADMINS",
};
